version: '3.8'
services:
  sae:
    build: apache
    container_name: sae
    volumes:
      - ./storage/sae:/var/www/html
    ports:
      - 8185:80
  postgres:
    build: postgres
    container_name: postgres
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tp12023
      - POSTGRES_USER=tp1
      - POSTGRES_DB=sae
      - PGDATA= ./storage/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=clement.trens1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8182:80
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
